### ISSUE TITLE
where to find the `http://localhost:4000/drugresistance/20210615?d=map` map?

### ISSUE THREAD

**Issue by liamxg** [xiaoyu518/PANGEA-Dashboard#1]
Dear @xiaoyu518,

Could I know where to find the `http://localhost:4000/drugresistance/20210615?d=map` map?

Thanks.

**Comment by xiaoyu518** [comment]
Hi,

This narrative is a template and cannot be visualised for public yet. All the trees that are open to the public can be found on https://www.pangea-hiv.org/resources/copy_of_tree-stories

**Comment by liamxg** [comment]
Dear @xiaoyu518,

That's really nice!

but I can not find any drug resistance data mapping on the tree?

BTW, how you align the env gene regions, as the region is hard to align, thanks.

**Comment by xiaoyu518** [comment]
DRM was tested on a different dataset and was not a part of the standard pipeline. The DRM analysis was not made public until all the results had been validated. 

env V1-V5 loops can be removed for better alignment. concatenated pairwise alignment to a reference can also improve the alignment.

**Comment by liamxg** [comment]
That's really helpful to me. Thanks. I usually using Mafft and manually edit the alignment.

As you said "we annotated the drug resistance data produced using [***] () to see the spread of drug resistance within the cohorts in these two datasets."

Could I know what software do you use to produce the drug resistance data and annotated  the spread of drug resistance within the cohorts in these two datasets." thanks.

**Comment by xiaoyu518** [comment]
I have addressed this question in a direct email to you. If you have any questions, we can directly communicate through email.
